[profile.default]
 src = "src"
 out = "out"
 libs = ["lib"]
 solc = "0.8.27"
 optimizer = true
 optimizer_runs = 200
 evm_version = "cancun"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/"
]

[rpc_endpoints]
 arbitrum-sepolia-rpc-url = "${ARBITRUM_SEPOLIA_RPC_URL}"
 sepolia-rpc-url = "${SEPOLIA_RPC_URL}"
 base-sepolia-rpc-url = "${BASE_SEPOLIA_RPC_URL}"
 bsc-testnet-rpc-url = "${BSC_TESTNET_RPC_URL}"
 avalanche-fuji-rpc-url = "${AVALANCHE_FUJI_RPC_URL}"
 holesky-rpc-url = "${HOLESKY_RPC_URL}"
 scroll-sepolia-rpc-url = "${SCROLL_SEPOLIA_RPC_URL}"
 soneium-minato-testnet-rpc-url = "${SONEIUM_MINATO_TESTNET_RPC_URL}"
 opbnb-testnet-rpc-url = "${OPBNB_TESTNET_RPC_URL}"

[etherscan]
 arbitrum-sepolia-key = { url = "https://api.etherscan.io/v2/api?chainid=421614", key = "${ETHERSCAN_API_KEY}" }
 sepolia-key = { url = "https://api.etherscan.io/v2/api?chainid=11155111", key = "${ETHERSCAN_API_KEY}" }
 bsc-testnet-key = { url = "https://api.etherscan.io/v2/api?chainid=97", key = "${ETHERSCAN_API_KEY}" }
 base-sepolia-key = { url = "https://api.etherscan.io/v2/api?chainid=84532", key = "${ETHERSCAN_API_KEY}" }
 scroll-sepolia-key = { url = "https://api.etherscan.io/v2/api?chainid=534351", key = "${ETHERSCAN_API_KEY}" }
 opbnb-testnet-key = { url = "https://api.etherscan.io/v2/api?chainid=5611", key = "${ETHERSCAN_API_KEY}" }
 holesky-key = { url = "https://api.etherscan.io/v2/api?chainid=17000", key = "${ETHERSCAN_API_KEY}" }
 avalanche-fuji-key = { url = "https://api.etherscan.io/v2/api?chainid=43113", key = "${ETHERSCAN_API_KEY}" }


#  localhost = "http://127.0.0.1:8545"
#  optSepolia = "${OPT_SEPOLIA_RPC_URL}"
#  seiAtlantic = "${SEI_ATLANTIC_RPC_URL}"
#  bitlayerTestnet = "${BITLAYER_TESTNET_RPC_URL}"
#  polygonAmoy = "${POLYGON_AMOY_RPC_URL}"
#  confluxEspace = "${CONFLUX_ESPACE_RPC_URL}"
#  lineaSepolia = "${LINEA_SEPOLIA_RPC_URL}"
#  coreTestnet = "${CORE_TESTNET_RPC_URL}"
#  morphHolesky = "${MORPH_HOLESKY_RPC_URL}"
#  soneiumMinato = "${SONEIUM_MINATO_RPC_URL}"
#  luksoTestnet = "${LUKSO_TESTNET_RPC_URL}"
#  cronosTestnet = "${CRONOS_TESTNET_RPC_URL}"
#  lumiaTestnet = "${LUMIA_TESTNET_RPC_URL}"
#  blastSepolia = "${BLAST_SEPOLIA_RPC_URL}"
#  mantleSepolia = "${MANTLE_SEPOLIA_RPC_URL}"
#  beraBartio = "${BERA_BARTIO_RPC_URL}"
#  lumeTestnet = "${PLUME_TESTNET_RPC_URL}"
#  vanguard = "${VANGUARD_RPC_URL}"
#  fireThunder = "${FIRE_THUNDER_RPC_URL}"
#  areonTestnet = "${AREON_TESTNET_RPC_URL}"
#  rariTestnet = "${RARI_TESTNET_RPC_URL}"
#  u2uTestnet = "${U2U_NEBULAS_TESTNET_RPC_URL}"
#  sonicTestnet = "${SONIC_TESTNET_RPC_URL}"
#  humanodeTestnet = "${HUMANODE_TESTNET_RPC_URL}"
#  redbellyTestnet = "${REDBELLY_TESTNET_RPC_URL}"
#  mantaPacific = "${MANTA_PACIFIC_RPC_URL}"
 
#  arbSepoliaKey = { url = "https://api-sepolia.arbiscan.io/api", chain = 421614, key = "${ARBISCAN_API_KEY}" }
#  sepoliaKey = { url = "https://api-sepolia.etherscan.io/api", chain = 11155111, key = "${ETHERSCAN_API_KEY}" }
#  baseSepoliaKey = { url = "https://api-sepolia.basescan.org/api", chain = 84532, key = "${BASE_API_KEY}" }
#  optSepoliaKey = { url = "https://api-sepolia-optimistic.etherscan.io/api", chain = 11155420, key = "${OPT_API_KEY}" }
#  bscTestnetKey = { url = "https://api-testnet.bscscan.com/api", chain = 97, key = "${BSC_API_KEY}" }
#  opBNBTestnetKey = { url = "https://api-opbnb-testnet.bscscan.com/api", chain = 5611, key = "${OPBNB_API_KEY}" }
#  seiAtlanticKey = { url = "https://seitrace.com/atlantic-2/api", chain = 1328, key = "${SEI_API_KEY}" }
#  bitlayerTestnetKey = { url = "https://api-testnet.btrscan.com/api", chain = 200810, key = "${BITLAYER_API_KEY}" }
#  avaxFujiKey = { url = "https://api-testnet.snowtrace.io/api", chain = 43113, key = "${AVAX_API_KEY}" }
#  polygonAmoyKey = { url = "https://api-amoy.polygonscan.com/api", chain = 80002, key = "${POLYGON_API_KEY}" }
#  sonicTestnetKey = { url = "https://api.sonic-testnet.explorers.guru/api", chain = 64165, key = "${SONIC_API_KEY}" }
#  confluxEspaceKey = { url = "https://evmapi-testnet.confluxscan.io/api", chain = 71, key = "${CONFLUX_API_KEY}" }
#  lineaSepoliaKey = { url = "https://api-sepolia.lineascan.build/api/v2", chain = 59141, key = "${LINEA_API_KEY}" }
#  soneiumMinatoKey = { url = "https://explorer.minato.soneium.org/api", chain = 1946, key = "${SONEIUM_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
